//! GENERATED by g2g-mcugen from graph `flagship`. Do not edit by hand;
//! regenerate with `g2g-mcugen <graph>.yaml`. This is the monomorphized
//! static MCU pipeline: heap-free, no `dyn`, ring sizes computed from the
//! graph's frame geometry.

use core::hint::black_box;
use g2g_core::staticpool::StaticLendRing;
use g2g_core::{AudioFormat, Caps, Chain, MediaClock, SinkChain, SourceChain, run_sources_fanin_sink};
use g2g_mcu::{FrameGrabber, G711Enc, GrabberSrc, Law, Mixer, PacketSender, PcmConvert, Resampler, RtpSink, SampleRate};

pub const FRAME_NS: u64 = 10000000;
pub const FRAMES: u32 = 50;
/// Total ring memory this graph statically owns.
pub const RING_BYTES_TOTAL: usize = 3440;

/// Negotiate the fan-in link's `Caps::Audio` (both sides black-boxed so
/// the audio arm of `Caps::intersect` stays in the archive for the proofs).
fn negotiate_fanin_link() -> Option<Caps> {
    let mk = || Caps::Audio { format: AudioFormat::PcmS16Le, channels: 1, sample_rate: 8000 };
    black_box(mk()).intersect(&black_box(mk())).ok()
}

/// Run the graph. Peripheral seams (the capture grabbers, then the sink's
/// output seam) are taken in the documented order; a board supplies HAL
/// impls, a proof harness supplies mocks.
pub async fn run_flagship_with<G0, G1, S>(grab_cap_a: G0, grab_cap_b: G1, sender: S) -> S
where
    G0: FrameGrabber,
    G1: FrameGrabber,
    S: PacketSender, {
    if negotiate_fanin_link().is_none() {
        return sender;
    }
    let ring_cap_a: StaticLendRing<1, 160> = StaticLendRing::new();
    let ring_cap_b: StaticLendRing<1, 1920> = StaticLendRing::new();
    let ring_conv: StaticLendRing<1, 960> = StaticLendRing::new();
    let ring_rs: StaticLendRing<1, 160> = StaticLendRing::new();
    let ring_mix: StaticLendRing<1, 160> = StaticLendRing::new();
    let ring_enc: StaticLendRing<1, 80> = StaticLendRing::new();

    // SAFETY: every ring above outlives the graph; the runner drains the
    // pipeline (each lent frame dropped in its iteration) before this future
    // completes and drops the rings.
    let cap_a = unsafe { GrabberSrc::with_ring(grab_cap_a, &ring_cap_a, FRAME_NS) }.with_frame_limit(FRAMES);
    let cap_b = unsafe { GrabberSrc::with_ring(grab_cap_b, &ring_cap_b, FRAME_NS) }.with_frame_limit(FRAMES);
    let conv = unsafe { PcmConvert::with_ring(&ring_conv) };
    let rs = unsafe { Resampler::with_ring(SampleRate::Hz48000, SampleRate::Hz8000, &ring_rs) };
    let mix = unsafe { Mixer::with_ring(16384, 16384, &ring_mix) };
    let enc = unsafe { G711Enc::with_ring(Law::Mulaw, &ring_enc) };
    let mut rtp = RtpSink::new(sender, MediaClock::audio(8000), 0, 0x67676767, 0);

    let _ = run_sources_fanin_sink(cap_a, SourceChain(cap_b, Chain(conv, rs)), mix, SinkChain(enc, &mut rtp)).await;
    rtp.free()
}
