//! M646/M648 proof: two flagship graphs as GENERATED by `g2g-mcugen`, one per
//! catalog. The `audio` and `video` modules are the compiler's output (checked
//! in, regenerated and diffed in CI); this crate drives each with the same mock
//! peripherals the hand-written references use, so the host tests in
//! `tests/equivalence.rs` can assert each generated pipeline's wire output
//! equals its reference checksum byte-for-byte:
//!
//! - `audio`: `capture -> convert -> resample -> mix -> encode -> RTP`, driven
//!   with the reference tone grabbers and a checksumming RTP sender; matches
//!   `noalloc_pipeline::audio::AUDIO_EXPECTED_CHECKSUM`.
//! - `video`: `camera -> SPI display`, driven with the reference pattern
//!   grabber and stub panel bus; matches `noalloc_pipeline::EXPECTED_CHECKSUM`
//!   (the reference's byte no-op transform makes camera->display equivalent).
//!
//! Together they show `g2g-mcugen` is a general MCU graph compiler, not an
//! audio-only one. `no_std` so both generated graphs are exercised in the same
//! no-alloc dependency config as the references: this crate builds only if the
//! emitted pipelines are genuinely heap-free.

#![no_std]

pub mod audio;
pub mod video;

use noalloc_pipeline::audio::{tone_a, tone_b, SumSender};
use noalloc_pipeline::{pattern_grabber, NoDelay, StubBus};

/// Run the generated flagship audio graph with the reference capture
/// peripherals and a checksumming sender; returns the wire checksum
/// (comparable to `noalloc_pipeline::audio::AUDIO_EXPECTED_CHECKSUM`).
pub fn run_audio_generated() -> u64 {
    g2g_core::drive_ready(audio::run_flagship_with(tone_a(), tone_b(), SumSender::default()))
        .map(|s| s.checksum())
        .unwrap_or(0)
}

/// Run the generated flagship display graph with the reference camera and stub
/// panel bus; returns the bus's wire checksum (comparable to
/// `noalloc_pipeline::EXPECTED_CHECKSUM`). The generated graph's SPI/DC seams
/// borrow the bus, so it outlives the run and the checksum is readable after.
pub fn run_video_generated() -> u64 {
    let bus = StubBus::new();
    let _ = g2g_core::drive_ready(video::run_display_with(
        pattern_grabber(),
        bus.spi(),
        bus.dc(),
        NoDelay,
    ));
    bus.checksum()
}
