//! GENERATED by g2g-mcugen from graph `display`. Do not edit by hand;
//! regenerate with `g2g-mcugen <graph>.yaml`. This is the monomorphized
//! static MCU pipeline: heap-free, no `dyn`, ring sizes computed from the
//! graph's frame geometry.

use g2g_core::staticpool::StaticLendRing;
use g2g_core::{run_source_sink};
use g2g_mcu::{FrameGrabber, GrabberSrc, SpiDisplaySink};

pub const FRAME_NS: u64 = 33333333;
pub const FRAMES: u32 = 64;
/// Total ring memory this graph statically owns.
pub const RING_BYTES_TOTAL: usize = 64;

/// Run the graph. Peripheral seams (the capture grabbers, then the sink's
/// output seam) are taken in the documented order; a board supplies HAL
/// impls, a proof harness supplies mocks.
pub async fn run_display_with<G0, SPI, DC, DLY>(grab_cam: G0, spi: SPI, dc: DC, mut delay: DLY)
where
    G0: FrameGrabber,
    SPI: embedded_hal::spi::SpiDevice,
    DC: embedded_hal::digital::OutputPin,
    DLY: embedded_hal::delay::DelayNs, {
    let ring_cam: StaticLendRing<1, 64> = StaticLendRing::new();

    // SAFETY: every ring above outlives the graph; the runner drains the
    // pipeline (each lent frame dropped in its iteration) before this future
    // completes and drops the rings.
    let cam = unsafe { GrabberSrc::with_ring(grab_cam, &ring_cam, FRAME_NS) }.with_frame_limit(FRAMES);
    let mut disp = SpiDisplaySink::st7789(spi, dc, 4, 4);

    if disp.init(&mut delay).is_err() {
        return;
    }
    let _ = run_source_sink(cam, &mut disp).await;
}
