//! M158 fragmented-MP4 demux: `Fmp4Demux` recovers the Annex-B access units from
//! an fMP4 byte stream. The fixture is generated by `Mp4Mux` (the inverse), so
//! the test is a real round-trip: feed AUs in, mux to fMP4, demux back, compare.
//! Also feeds the bytes in tiny chunks to exercise box reassembly across frames.

#![cfg(feature = "std")]

use core::future::Future;
use core::pin::Pin;

use g2g_core::element::AsyncElement;
use g2g_core::frame::{Frame, FrameTiming, PipelinePacket};
use g2g_core::memory::{MemoryDomain, SystemSlice};
use g2g_core::{
    ByteStreamEncoding, Caps, Dim, G2gError, OutputSink, PushOutcome, Rate, VideoCodec,
};
use g2g_plugins::fmp4demux::Fmp4Demux;
use g2g_plugins::mp4mux::Mp4Mux;

fn h264_caps(w: u32, h: u32) -> Caps {
    Caps::CompressedVideo {
        codec: VideoCodec::H264,
        width: Dim::Fixed(w),
        height: Dim::Fixed(h),
        framerate: Rate::Fixed(30 << 16),
    }
}

#[derive(Default)]
struct CaptureSink {
    caps: Vec<Caps>,
    frames: Vec<Vec<u8>>,
}
impl OutputSink for CaptureSink {
    fn push<'a>(
        &'a mut self,
        packet: PipelinePacket,
    ) -> Pin<Box<dyn Future<Output = Result<PushOutcome, G2gError>> + 'a>> {
        Box::pin(async move {
            match packet {
                PipelinePacket::CapsChanged(c) => self.caps.push(c),
                PipelinePacket::DataFrame(f) => {
                    if let Some(s) = f.domain.as_system_slice() {
                        self.frames.push(s.to_vec());
                    }
                }
                _ => {}
            }
            Ok(PushOutcome::Accepted)
        })
    }
}

fn frame(bytes: Vec<u8>, pts_ns: u64, sequence: u64) -> Frame {
    Frame {
        domain: MemoryDomain::System(SystemSlice::from_boxed(bytes.into_boxed_slice())),
        timing: FrameTiming {
            pts_ns,
            dts_ns: pts_ns,
            duration_ns: 33_333_333,
            ..FrameTiming::default()
        },
        sequence,
        meta: Default::default(),
    }
}

/// The access units fed in: first carries SPS+PPS+IDR, the rest are P slices.
fn source_access_units() -> Vec<Vec<u8>> {
    let sps = [0x67u8, 0x42, 0xC0, 0x1E, 0x11, 0x22];
    let pps = [0x68u8, 0xCE, 0x3C, 0x80];
    let idr: Vec<u8> = [
        &[0, 0, 0, 1][..],
        &sps,
        &[0, 0, 0, 1],
        &pps,
        &[0, 0, 0, 1],
        &[0x65, 0xAA, 0xBB],
    ]
    .concat();
    let p = |fill: u8| [&[0, 0, 0, 1][..], &[0x41, fill, fill]].concat();
    vec![idr, p(1), p(2), p(3)]
}

/// Mux the access units to an fMP4 byte buffer via the `Mp4Mux` element,
/// concatenating the byte-stream frames it forwards downstream.
async fn make_fmp4(aus: &[Vec<u8>]) -> Vec<u8> {
    let mut mux = Mp4Mux::new();
    mux.configure_pipeline(&h264_caps(64, 48)).unwrap();
    let mut out = CaptureSink::default();
    for (i, au) in aus.iter().enumerate() {
        mux.process(
            PipelinePacket::DataFrame(frame(au.clone(), i as u64 * 33_333_333, i as u64)),
            &mut out,
        )
        .await
        .unwrap();
    }
    mux.process(PipelinePacket::Eos, &mut out).await.unwrap();
    out.frames.concat()
}

async fn demux(fmp4: &[u8], chunk: usize) -> CaptureSink {
    let mut dmx = Fmp4Demux::new();
    dmx.configure_pipeline(&Caps::ByteStream {
        encoding: ByteStreamEncoding::IsoBmff,
    })
    .unwrap();
    let mut sink = CaptureSink::default();
    for (seq, part) in fmp4.chunks(chunk).enumerate() {
        dmx.process(
            PipelinePacket::DataFrame(frame(part.to_vec(), 0, seq as u64)),
            &mut sink,
        )
        .await
        .unwrap();
    }
    dmx.process(PipelinePacket::Eos, &mut sink).await.unwrap();
    sink
}

#[tokio::test]
async fn demuxes_fmp4_from_mp4mux_roundtrip() {
    let aus = source_access_units();
    let fmp4 = make_fmp4(&aus).await;
    let sink = demux(&fmp4, fmp4.len()).await; // whole stream in one frame

    assert_eq!(
        sink.caps,
        vec![Caps::CompressedVideo {
            codec: VideoCodec::H264,
            width: Dim::Fixed(64),
            height: Dim::Fixed(48),
            framerate: Rate::Any,
        }],
        "moov drives one CapsChanged with the real codec + geometry"
    );
    assert_eq!(
        sink.frames, aus,
        "every access unit recovered, in order, byte-exact"
    );
}

#[tokio::test]
async fn reassembles_boxes_across_chunk_boundaries() {
    let aus = source_access_units();
    let fmp4 = make_fmp4(&aus).await;
    // 7-byte chunks split every box header and payload across frames.
    let sink = demux(&fmp4, 7).await;

    assert_eq!(
        sink.caps.len(),
        1,
        "geometry still recovered once despite fragmentation"
    );
    assert_eq!(
        sink.frames, aus,
        "buffered box reassembly yields the same access units"
    );
}
