#!/usr/bin/env python3
"""Generate the fixed-point polyphase coefficient tables for
g2g-mcu/src/resample_tables.rs (M641). Pure python (no numpy): a
Blackman-windowed sinc prototype per (L, M) pair over the telephony rate set
{8, 16, 48} kHz, deinterleaved phase-major, each phase branch normalized to
an exact Q14 unity sum (so DC gain is exactly 1.0 at every phase: no
periodic gain ripple), largest coefficient adjusted to absorb rounding.

Run from the repo root:  python3 tools/gen-resample-tables.py
It rewrites g2g-mcu/src/resample_tables.rs in place; the m641 test asserts
the invariants (per-phase sums, |coeff| bounds) against the checked-in file.
"""

import math

# Taps per phase. Interpolators (M=1) use K per phase over L phases
# (prototype length K*L); decimators (L=1) are single-phase with the
# anti-alias filter at the input rate, so K scales with M.
K_PER_PHASE = 32

# (name, L, M): the reduced ratios of the {8000, 16000, 48000} rate set.
PAIRS = [
    ("UP_2", 2, 1),    # 8k  -> 16k
    ("UP_3", 3, 1),    # 16k -> 48k
    ("UP_6", 6, 1),    # 8k  -> 48k
    ("DOWN_2", 1, 2),  # 16k -> 8k
    ("DOWN_3", 1, 3),  # 48k -> 16k
    ("DOWN_6", 1, 6),  # 48k -> 8k
]

Q = 14  # Q14: headroom for sinc overshoot above the per-phase sum
UNITY = 1 << Q


def blackman(n, N):
    x = 2.0 * math.pi * n / (N - 1)
    return 0.42 - 0.5 * math.cos(x) + 0.08 * math.cos(2.0 * x)


def prototype(L, M):
    """Windowed-sinc lowpass at the upsampled rate fs*L, length K*L for
    interpolators / K*M taps for decimators, cutoff below the narrower
    Nyquist."""
    mx = max(L, M)
    N = K_PER_PHASE * L if M == 1 else K_PER_PHASE * M
    fc = 0.42 / mx  # cycles/sample at rate fs*L; 0.42: transition margin
    c = (N - 1) / 2.0
    h = []
    for n in range(N):
        t = n - c
        s = 2.0 * fc if t == 0 else math.sin(2.0 * math.pi * fc * t) / (math.pi * t)
        h.append(s * blackman(n, N))
    return h


def phases(L, M):
    """Deinterleave to phase-major Q14 i16, each phase branch summing to
    exactly UNITY."""
    h = prototype(L, M)
    n_phases = L
    k = len(h) // L
    out = []
    for p in range(n_phases):
        branch = [h[p + i * L] for i in range(k)]
        scale = UNITY / sum(branch)
        q = [round(c * scale) for c in branch]
        # absorb the rounding remainder into the largest-|.| coefficient so
        # the sum is exactly UNITY
        q[max(range(k), key=lambda i: abs(q[i]))] += UNITY - sum(q)
        assert sum(q) == UNITY
        assert all(-32768 <= c <= 32767 for c in q), "Q14 headroom exceeded"
        # the engine accumulates in i32: keep sum(|h|)*32767 well inside it
        assert sum(abs(c) for c in q) < 60000, "i32 accumulator headroom"
        out.append(q)
    return out


def emit():
    lines = [
        "//! Polyphase coefficient tables for [`crate::resample`] (M641),",
        "//! GENERATED by tools/gen-resample-tables.py: Blackman-windowed sinc,",
        "//! phase-major, Q14, each phase branch summing to exactly 1<<14 (DC",
        "//! gain exactly unity at every phase). Regenerate with the script;",
        "//! `m641_resample.rs` asserts the invariants against this file.",
        "",
        "/// Q shift of the coefficient tables.",
        "pub const COEFF_SHIFT: u32 = %d;" % Q,
        "",
    ]
    for name, L, M in PAIRS:
        ph = phases(L, M)
        k = len(ph[0])
        flat = [c for branch in ph for c in branch]
        lines.append("/// L=%d, M=%d, %d taps per phase, phase-major." % (L, M, k))
        lines.append("pub const %s: crate::resample::RateTable = crate::resample::RateTable {" % name)
        lines.append("    l: %d," % L)
        lines.append("    m: %d," % M)
        lines.append("    taps: %d," % k)
        lines.append("    coeffs: &[")
        for i in range(0, len(flat), 12):
            lines.append("        " + ", ".join(str(c) for c in flat[i : i + 12]) + ",")
        lines.append("    ],")
        lines.append("};")
        lines.append("")
    with open("g2g-mcu/src/resample_tables.rs", "w") as f:
        f.write("\n".join(lines))
    print("wrote g2g-mcu/src/resample_tables.rs")


if __name__ == "__main__":
    emit()
